# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	target 'TodaysWorld' do
  # add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'lottie-ios'
  # Pods for BusBooking

end


